### ISSUE TITLE
Meeting Notes: Tue 6th Feb 2024

### ISSUE THREAD

**Issue by shsingh** [f5devcentral/f5xc-backup-restore-utils#2]
**Attendees:**

@jeraldcheong 
@shsingh 

**Notes:**

- Discuss requirements and features missing
- Define pre-requisites for script
- Dependency checking (order of operations) -> define manually for now
- Add ability to define output directory
- features will be added using git branches/tags
- leverage Github Actions for any CI/CD
- update repository with information on logging security/vulnerability, license and support information

**Comment by shsingh** [comment]
List of tasks to complete:

- [ ] update README with pre-requisites for script
- [ ] create instructions for installation of script
- [ ] add ability to define output directory in script

**Comment by jeraldcheong** [comment]
Outputs from running the scripts.

Backup:
❯ python3 f5xc-backup-restore.py -a backup -p /home/jcheong/working/F5_backup --n jcheong-testing
/home/jcheong/working/F5_backup/f5xc-backup-20240221_070526
/home/jcheong/working/F5_backup
 
======================================================================================================================
[STARTED]     Date: 2024-02-21 07:05:26 UTC     Tenant: f5-xctestdrive     TASK: BACKUP       Namespace: jcheong-testing
======================================================================================================================
[jcheong-testing] Backing up HTTP Loadbalancer object [jcheong-test-lb] ..... DONE
[jcheong-testing] Backing up Origin Pool object [jcheong-test-originpool] ..... DONE
[jcheong-testing] Backing up Health Check object [jcheong-test-hc] ..... DONE
[jcheong-testing] Backing up App Firewall object [jcheong-testing-appfw] ..... DONE
[jcheong-testing] Backing up Malicious User Mitigation object [jcheong-test-maluser-policy] ..... DONE
================================================================================================================
[COMPLETED]   Date: 2024-02-21 07:05:58 UTC     Tenant: f5-xctestdrive
================================================================================================================

Restore:
❯ python3 f5xc-backup-restore.py -a restore -p /home/jcheong/working/F5_backup/f5xc-backup-20240221_070526/ -n jcheong-testing
/home/jcheong/working/F5_backup/f5xc-backup-20240221_070526//f5xc-backup-20240221_070950
/home/jcheong/working/F5_backup/f5xc-backup-20240221_070526/
==================================================================================================================================
[STARTED]     Date: 2024-02-21 07:09:50 UTC      Tenant: f5-xctestdrive    TASK: RESTORE      Namespace: jcheong-testing
====================================================================================================================================
[jcheong-testing] Restoring Health Check object from file [ jcheong-testing_healthcheck-jcheong-test-hc.json ] ..... DONE
[jcheong-testing] Restoring Origin Pool object from file [ jcheong-testing_origin_pool-jcheong-test-originpool.json ] ..... DONE
[jcheong-testing] Restoring App Firewall object from file [ jcheong-testing_app_fw-jcheong-testing-appfw.json ] ..... DONE
[jcheong-testing] Restoring HTTP LoadBalancer object from file [ jcheong-testing_http_lb-jcheong-test-lb.json ] ..... DONE
[jcheong-testing] Restoring Malicious User Policy object from file [ jcheong-testing_malicioususer_policy-jcheong-test-maluser-policy.json ] ..... DONE
================================================================================================================
[COMPLETED]   Date: 2024-02-21 07:10:20 UTC     Tenant: f5-xctestdrive
================================================================================================================
